-- Add store_id to mvp_sales if not exists
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'mvp_sales' and column_name = 'store_id') then
    alter table public.mvp_sales add column store_id uuid; -- Loosely typed to avoid FK error if stores missing, but ideally references public.stores(id)
  end if;
end $$;

-- Create sale_items table
create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id uuid references public.mvp_sales(id) on delete cascade not null,
  name text not null,
  quantity integer not null,
  unit_price integer not null,
  total_price integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for sale_items
alter table public.sale_items enable row level security;

create policy "Users can view their own sale items"
on public.sale_items for select
using (
  exists (
    select 1 from public.mvp_sales
    where mvp_sales.id = sale_items.sale_id
    and mvp_sales.user_id = auth.uid()
  )
);

create policy "Users can insert their own sale items"
on public.sale_items for insert
with check (
  exists (
    select 1 from public.mvp_sales
    where mvp_sales.id = sale_items.sale_id
    and mvp_sales.user_id = auth.uid()
  )
);

create policy "Users can delete their own sale items"
on public.sale_items for delete
using (
  exists (
    select 1 from public.mvp_sales
    where mvp_sales.id = sale_items.sale_id
    and mvp_sales.user_id = auth.uid()
  )
);
